services:
  - type: web
    name: hoe-laat
    runtime: ruby
    buildCommand: |
      bundle install
      yarn install
      yarn build:css
    startCommand: bundle exec rails server
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_LOG_TO_STDOUT
        value: enabled
